main: joni.status4discordmc.Status4Discord
name: Status4Discord
version: 1.1
author: LasaJoni
api-version: 1.18
load: STARTUP
description: A discord bot, showing the current status of your server as embed, activity and more.
softdepend: [PlaceholderAPI]

commands:
  status4discord:
    description: Command for status4discord

permissions:
  status4discord.admin:
    description: Use /status4discord reload and /status4discord restart
    default: op
